# Generated by Django 4.2.7 on 2025-06-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sejm_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('club', models.CharField(blank=True, max_length=50, null=True)),
                ('district_name', models.CharField(blank=True, max_length=50, null=True)),
                ('district_num', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('voivodeship', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'parliament"."members',
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstain', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=50, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('majority_type', models.CharField(blank=True, max_length=50, null=True)),
                ('majority_votes', models.IntegerField(blank=True, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('not_participating', models.IntegerField(blank=True, null=True)),
                ('present', models.IntegerField(blank=True, null=True)),
                ('sitting', models.IntegerField(blank=True, null=True)),
                ('sitting_day', models.IntegerField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('total_voted', models.IntegerField(blank=True, null=True)),
                ('voting_number', models.IntegerField(blank=True, null=True)),
                ('yes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parliament"."votings',
                'unique_together': {('voting_number', 'sitting_day', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id_api', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_choice', models.CharField(choices=[('YES', 'Za'), ('NO', 'Przeciw'), ('ABSTAIN', 'Wstrzymał się'), ('NOT_PARTICIPATING', 'Nie brał udziału')], max_length=20)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_votes', to='sejm_app.member')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_votes', to='sejm_app.voting')),
            ],
            options={
                'db_table': 'parliament"."individual_votes',
                'unique_together': {('voting', 'member')},
            },
        ),
    ]
